<?php

namespace app\admin\model;

use think\Model;
use think\Session;

class Admin extends Model
{
    //
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 检查用户登录
     * @return array|bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkLogin()
    {
        $userName = trim(input('post.username'));
        $password = trim(input('post.password'));
        $captcha = trim(input('post.captcha'));
        if (captcha_check($captcha)){
            $user = $this->where(['user_name'=>$userName,'work_status'=>1])->find();
            if (!empty($user)){
                if ($user['password'] == md5($password.$user['safety_code'])){
                    Session::set("ADMIN_PASS",$user);
                    $user->last_time=date("Y-m-d H:i:s",time());
                    $user->last_ip=request()->ip();
                    $user->save();
                    return ajaxReturn(lang('login successful'),3);
                }else{
                    return ajaxReturn(lang('wrong password'),2);
                }
            }else{
                return ajaxReturn(lang('User does not exist'),1);
            }
            return true;
        }else{
            return ajaxReturn(lang('captcha is error'),0);
        }
    }

    /**
     * 获取用户信息
     * @param $name
     * @return bool|false|\PDOStatement|string|\think\Collection
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getUserInfo($name)
    {
        if ($name){
            $result = $this->where('user_name',$name)->select();
            return $result;
        }else{
            return false;
        }
    }
    /**
     * 检查用户
     * @param $name
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getUser($name)
    {
        if ($name){
            $result = $this->where(['user_name'=>$name,'work_status'=>1])->find();
            if (empty($result)){
                return false;
            }else{
                return true;
            }
        }else{
            return false;
        }
    }

    /**
     * 检查密码
     * @param $username
     * @param $password
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkPassword($username,$password)
    {
        if ($username && $password){
            $user = $this->where(['user_name'=>$username])->find();
            if ($user['password'] == $password){
                return true;
            }else{
                return false;
            }
        }else{
            return false;
        }
    }

    /**
     * 记录登录日志
     * @param array $data
     * @return bool
     */
    public function recordLog($data=[])
    {
        if (!empty($data)){
            $result = $this->update($data);
            if ($result){
                return true;
            }else{
                return false;
            }
        }else{
            return false;
        }
    }

}
